services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php

  php:
    image: thecodingmachine/php:8.2-v4-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      PHP_EXTENSIONS: "pdo pdo_mysql mysqli gd"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: only
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  database:

networks:
  app-network: